name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build Angular app
        run: npm install && npm run build

      - name: Deploy to Google Cloud Storage
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud
        run: |
          echo ${{ secrets.GCP_SA_KEY }} | base64 --decode > keyfile.json
          gcloud auth activate-service-account --key-file=keyfile.json
          gcloud config set project codefest-389002

      - name: Deploy to Cloud Storage
        run: gsutil -m rsync -R ./dist gs://angular-advanced-ai
