name: Deploy to Google Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Build Angular app
        run: npm install && npm run build

      - name: Configure gcloud
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          version: 'latest'
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          project_id: codefest-389002

      - name: Deploy to Cloud Storage
        run: gsutil -m rsync -R ./dist gs://angular-advanced-ai
